import genRecibo from "./genRecibo"
import delRecibo from "./delRecibo"
import addComi from "./addComi"
import editComi from "./editComi"
import editFile from "./editFile"
import editFileG from "./editFileG"
import deleteFile from "./deleteFile"
import upLoadD from "./upLoadD"
import upLoadDG from "./upLoadDG"
export{genRecibo,editFile,editFileG,deleteFile,delRecibo,addComi,editComi,upLoadD,upLoadDG}